### PR TITLE
Dynamic Sorted Arrays (Issue #8) + Animation Support

### PR DESCRIPTION
**Pull request by RPGHacker**
-Added: Dynamic sorted arrays with binary search & insertion for quickly
finding tiles in a big array (see issue #8)
-Added: Animation support for tiles (tmx_frame)
-Restructured tiles list into array to make use of new sorted array
-Changed tile id into tile gid to use for sort key
-Other minor changes

### CODE REVIEW

**Comment by RPGHacker** [comment]
Alright, so here is my implementation of a dynamic sorted array as suggested in issue #8. I restructured many things to make use of this new array. I didn't make a performance test or anything, so I can't tell if it's actually faster, but I'm sure that at least with a high number of tmx_tile instances, this should definitely be faster than a linked list (at the cost of potentially slightly slower map loading, due to re-allocating of arrays when resizing). While I was at it, I also added support for animations, which were introduced in Tiled some time ago, to the library. Let me know if there is anything I overlooked and/or need to improve.

**Comment by baylej** [comment]
Hi @RPGHacker,

Thank you for your contribution, I will review it soon.
Keep in mind that it's better to create one pull request per feature (if one feature gets accepted but not the other).
I am not able to find documentation for the animated tile feature, could you please drop me a link here ?

Regards,
Jonathan.

**Comment by RPGHacker** [comment]
Is it actually possible to select only certain commits for a pull request? Whenever I try, GitHub automatically adds all my commits to the pull request.
As for the animations, they probably forgot to add the animation support to the documentation. It's a relatively new feature (I think it was introduced some time in 2014). In any case, a lengthy discussion about Tiled animations can be found here:
https://github.com/bjorn/tiled/issues/57
If you have the newest version of Tiled, the Tile Animation Editor can be found somewhere in the menu bar (not sure under which category since I don't have Tiled here right now, but it's easy to find).

**Comment by baylej** [comment]
You have to create a branch and implement the new feature in that branch, this is the so called *feature branch*.
See https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow

**Comment by RPGHacker** [comment]
Alright. I'll keep that in mind for next time!

**Comment by bjorn** [comment]
> Alright, so here is my implementation of a dynamic sorted array as suggested in issue #8.

I wonder a little why the bother with the sorted array, since the global list of tiles is guaranteed not to have any holes. So you should be fine by only appending tiles to the end. On Tiled master, there is also a `tilecount` attribute saved for each `tileset` element, which could be used to reduce reallocations of the tiles array.

Or does this library avoid allocating `tmx_tile` instances in some situations, like when there are no properties and no per-tile image defined?

> As for the animations, they probably forgot to add the animation support to the documentation.

Oh noes, indeed I totally forgot to documented it! I've opened issue bjorn/tiled#985 about it so that I'll hopefully remember to get around to that...

**Comment by bjorn** [comment]
> I wonder a little why the bother with the sorted array, since the global list of tiles is guaranteed not to have any holes.

Hrm, just looking at the code, I realize now that at least i made it a little bit non-obvious and possibly somewhat hard to implement this, at least before the addition of the `tilecount` information...

**Comment by RPGHacker** [comment]
> I wonder a little why the bother with the sorted array, since the global list of tiles is guaranteed not to have any holes. So you should be fine by only appending tiles to the end.

Oh, I didn't know that and didn't read the documentation on this. Didn't want to make any assumptions, either, so I just made it a sorted array. I think it isn't a big problem, though, since binary search is quite fast and therefore we're not wasting much performance here. And who knows, maybe the sorted array will come in handy some other time.

> Or does this library avoid allocating tmx_tile instances in some situations, like when there are no properties and no per-tile image defined?

That's actually true, the library only takes what it can find in the tmx/json file and if there is no entry on a tile at all, it just ignores that tile. I guess it could still work as a regular dynamic array, but yeah, shame on me for not reading any documentation. :P

> I realize now that at least i made it a little bit non-obvious and possibly somewhat hard to implement this (especially in the JSON format),

Yeah, the one thing that was a bit problematic here was that "tileproperties" and "tiles" are (were?) two seperate arrays, while they should only be a single combined array ("tileproperties" should be a child element of "tiles" or, to be more precise, a child element of a tile in the tiles array). This is what lead to the problem in the first place since tiles could not just be inserted into the list since they could have already been present there. And I guess that was also the main reason for going with a sorted array, since while parsing "tileproperties" you might create a certain list of tiles then, while parsing "tiles", might have to insert new tiles in the middle of the array.

**Comment by baylej** [comment]
Hi @bjorn and @RPGHacker ,

Yep the first problem was: when accessing the tiles properties, images, ... each rendering loop, linked list are too slow and quite cumbersome to use.

The sorted array is much better, and the sparse array is the fastest (random access) and easiest to use.

**Pull request closed without merging**
